### ISSUE TITLE
signing the project

### ISSUE THREAD

**Issue by deadpoolcode1** [Kynetics/uf-android-client#11]
when I try to deploy the project I get:

pm install /data/uf-client-service.apk                                   <
Failure [INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: Reconciliation failed...: Reconcile failed: Package com.kynetics.uf.service has no signatures that match those in shared user android.uid.system; ignoring!]

I tried to sign with device platform key: 

java -Xmx2048m -Djava.library.path=out/host/linux-x86/lib64 -jar out/host/linux-x86/framework/signapk.jar -w build/target/product/security/testkey.x509.pem build/target/product/security/testkey.pk8  /tmp/uf-client-service-debug.apk /tmp/uf-client-service-signed.apk

that did not resolve the issue

please advice

**Comment by diegorondini** [comment]
Hi,

please keep in mind pre-built packages are already signed with either NXP or AOSP keys:
https://github.com/Kynetics/uf-android-client/releases

You need to understand which set of keys your Android build is using and pick the correct package or sign with your own key.

Please note the command line you provided signs with the **testkey**, rather than the **platform** key (which is generally available in the same folder).

Regards
